# Generated by Django 4.2.3 on 2023-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslocation',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adslocation',
            name='max_visits',
            field=models.IntegerField(default=1),
        ),
    ]
